package com.example.spetify

object Localization {
    private val en = mapOf(
        "queue" to "Queue",
        "home" to "Home",
        "directory" to "Directory",
        "library" to "Library",
        "search" to "Search",
        "settings" to "Menu",
        "app_settings" to "Settings",
        "language" to "Language",
        "interface" to "Interface",
        "audio" to "Audio",
        "help_info" to "Help & Info",
        "sleep_timer" to "Sleep timer",
        "vocal_remover" to "Vocal remover",
        "close_app" to "Close app",
        "current_queue" to "Current Queue",
        "clear_queue" to "Clear Queue",
        "songs" to "songs",
        "sort_by" to "Sort by",
        "title_az" to "Title (A-Z)",
        "artist_az" to "Artist (A-Z)",
        "duration_longest" to "Duration (Longest)",
        "recently_added" to "Recently Added",
        "filename" to "Filename",
        "shuffle_all" to "Shuffle All",
        "share_songs" to "Share songs",
        "save_album_art" to "Save Album Art",
        "edit_tags" to "Edit Tags",
        "song_info" to "Song Info",
        "add_to_playlist" to "Add to Playlist",
        "delete_permanently" to "Delete permanently",
        "cancel" to "Cancel",
        "ok" to "OK",
        "select_language" to "Select Language",
        "select_theme" to "Select Theme",
        "coming_soon" to "Coming soon",
        "no_lyrics" to "No lyrics available",
        "loading_lyrics" to "Loading lyrics...",
        "search_hint" to "Search tracks or artists...",
        "empty_queue" to "Your queue is empty",
        "folder_actions" to "Folder Actions",
        "play_all" to "Play All",
        "shuffle" to "Shuffle",
        "back" to "Back",
        "version" to "Version",
        "developer" to "Developer",
        "about_desc" to "A high-performance music player with advanced tagging and sorting features.",
        "auto_scroll_queue" to "Auto-scroll to playing song",
        "auto_scroll_desc" to "Automatically center the current track in the queue list",
        "sleep_timer_title" to "Sleep Timer",
        "off" to "Off",
        "min" to "min",
        "timer_set" to "Timer set for",
        "timer_cancelled" to "Sleep timer cancelled"
    )

    private val ru = mapOf(
        "queue" to "Очередь",
        "home" to "Главная",
        "directory" to "Проводник",
        "library" to "Библиотека",
        "search" to "Поиск",
        "settings" to "Меню",
        "app_settings" to "Настройки",
        "language" to "Язык",
        "interface" to "Интерфейс",
        "audio" to "Аудио",
        "help_info" to "Справка",
        "sleep_timer" to "Таймер сна",
        "vocal_remover" to "Удаление вокала",
        "close_app" to "Выйти",
        "current_queue" to "Текущая очередь",
        "clear_queue" to "Очистить очередь",
        "songs" to "песен",
        "sort_by" to "Сортировка",
        "title_az" to "Название (А-Я)",
        "artist_az" to "Исполнитель (А-Я)",
        "duration_longest" to "Длительность (сначала длинные)",
        "recently_added" to "Недавно добавленные",
        "filename" to "Имя файла",
        "shuffle_all" to "Перемешать всё",
        "share_songs" to "Поделиться песнями",
        "save_album_art" to "Сохранить обложку",
        "edit_tags" to "Изменить теги",
        "song_info" to "Инфо о песне",
        "add_to_playlist" to "Добавить в плейлист",
        "delete_permanently" to "Удалить навсегда",
        "cancel" to "Отмена",
        "ok" to "ОК",
        "select_language" to "Выберите язык",
        "select_theme" to "Выберите тему",
        "coming_soon" to "Скоро будет",
        "no_lyrics" to "Текст песни отсутствует",
        "loading_lyrics" to "Загрузка текста...",
        "search_hint" to "Поиск треков или артистов...",
        "empty_queue" to "Очередь пуста",
        "folder_actions" to "Действия с папкой",
        "play_all" to "Играть всё",
        "shuffle" to "Перемешать",
        "back" to "Назад",
        "version" to "Версия",
        "developer" to "Разработчик",
        "about_desc" to "Высокопроизводительный плеер с продвинутым управлением тегами и очередями.",
        "auto_scroll_queue" to "Автопрокрутка в очереди",
        "auto_scroll_desc" to "Автоматически центрировать текущую песню в списке очереди",
        "sleep_timer_title" to "Таймер сна",
        "off" to "Выкл.",
        "min" to "мин",
        "timer_set" to "Таймер установлен на",
        "timer_cancelled" to "Таймер сна отменен"
    )

    fun getString(key: String, lang: String): String {
        return if (lang == "ru") ru[key] ?: key else en[key] ?: key
    }
}
